/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConsultDataController;
import util.ConsultDataTableModel;

/**
 *
 * @author tharl
 */
public class ConsultDataScreen extends javax.swing.JInternalFrame {

    ConsultDataTableModel Modelo;
    
    ConsultDataController consultDataController = new ConsultDataController();
    
    PersonScreen personScreen = new PersonScreen();
    EventRoomScreen eventRoomScreen = new EventRoomScreen();
    CoffeSpaceScreen coffeSpaceScreen = new CoffeSpaceScreen();
    
    // Carrega a tabela de pessoas
    public void LoadTableConsult() {
        Modelo = new ConsultDataTableModel(ConsultDataController.getDados());
        tabelaDados.setModel(Modelo);

        tabelaDados.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaDados.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelaDados.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    // Carrega a tabela de pessoas
    public void LoadTableConsultSegunda() {
        Modelo = new ConsultDataTableModel(ConsultDataController.getDadosSegundo());
        tabelaDadosSegunda.setModel(Modelo);

        tabelaDadosSegunda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaDadosSegunda.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelaDadosSegunda.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    
    /**
     * Creates new form ConsultDataScreen
     */
    public ConsultDataScreen() {
        initComponents();
        LoadTableConsult();
        LoadTableConsultSegunda();
        
        personScreen.LoadTable();
        eventRoomScreen.LoadTableRoom();
        coffeSpaceScreen.LoadTableSpace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTabelaDados = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        scrollPaneTabelaDados1 = new javax.swing.JScrollPane();
        tabelaDadosSegunda = new javax.swing.JTable();
        labelTitleUm = new javax.swing.JLabel();
        LabelTitleDois = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consultar");
        setPreferredSize(new java.awt.Dimension(468, 447));

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pessoas", "Salas", "Espaços de Café"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTabelaDados.setViewportView(tabelaDados);

        tabelaDadosSegunda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pessoas", "Salas", "Espaços de Café"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTabelaDados1.setViewportView(tabelaDadosSegunda);

        labelTitleUm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitleUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleUm.setText("1ª Etapa do Treinamento");

        LabelTitleDois.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelTitleDois.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitleDois.setText("2ª Etapa do Treinamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneTabelaDados1)
            .addComponent(scrollPaneTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTitleDois)
                    .addComponent(labelTitleUm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTitleDois)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTabelaDados1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitleDois;
    private javax.swing.JLabel labelTitleUm;
    private javax.swing.JScrollPane scrollPaneTabelaDados;
    private javax.swing.JScrollPane scrollPaneTabelaDados1;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JTable tabelaDadosSegunda;
    // End of variables declaration//GEN-END:variables
}
