/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CoffeSpaceController;
import util.CoffeSpaceTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tharlys
 */
public class CoffeSpaceScreen extends javax.swing.JInternalFrame {

    CoffeSpaceTableModel Modelo;
    
    public void LoadTableSpace() {
        Modelo = new CoffeSpaceTableModel(CoffeSpaceController.getSpaces());
        tabelaEspacos.setModel(Modelo);
        
        tabelaEspacos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaEspacos.getColumnModel().getColumn(1).setPreferredWidth(100);
    }
    
    public void Botoes(boolean N, boolean S, boolean C) {
        botaoNovoEspaco.setEnabled(N);
        botaoSalvarEspaco.setEnabled(S);
        botaoCancelarEspaco.setEnabled(C);
    }
    
    public void ManipulaCampo(String modo) {
        switch(modo) {
            case "Limpa":
                campoNomeEspaco.setText("");
                campoLotacaoEspaco.setText("");
                break;
            case "Bloqueia":
                campoNomeEspaco.setEnabled(false);
                campoLotacaoEspaco.setEnabled(false);
                break;
            case "Desbloqueia":
                campoNomeEspaco.setEnabled(true);
                campoLotacaoEspaco.setEnabled(true);
                break;
            default:
                System.out.println("Modo inválido");
        }
    }
    
    /**
     * Creates new form CoffeSpaceScreen
     */
    public CoffeSpaceScreen() {
        initComponents();
        LoadTableSpace();
        ManipulaCampo("Bloqueia");
        Botoes(true,false,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneEspacoCafe = new javax.swing.JScrollPane();
        tabelaEspacos = new javax.swing.JTable();
        panelCampos = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelLotacao = new javax.swing.JLabel();
        campoNomeEspaco = new javax.swing.JTextField();
        campoLotacaoEspaco = new javax.swing.JTextField();
        panelBotoes = new javax.swing.JPanel();
        botaoNovoEspaco = new javax.swing.JButton();
        botaoSalvarEspaco = new javax.swing.JButton();
        botaoCancelarEspaco = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Espaços de Café");
        setPreferredSize(new java.awt.Dimension(468, 447));

        tabelaEspacos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Lotação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEspacos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEspacosMouseClicked(evt);
            }
        });
        scrollPaneEspacoCafe.setViewportView(tabelaEspacos);

        panelCampos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNome.setText("Nome:");

        labelLotacao.setText("Lotação:");

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelLotacao))
                .addGap(26, 26, 26)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNomeEspaco)
                    .addComponent(campoLotacaoEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNomeEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLotacao)
                    .addComponent(campoLotacaoEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botaoNovoEspaco.setText("Novo");
        botaoNovoEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoEspacoActionPerformed(evt);
            }
        });

        botaoSalvarEspaco.setText("Salvar");
        botaoSalvarEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarEspacoActionPerformed(evt);
            }
        });

        botaoCancelarEspaco.setText("Cancelar");
        botaoCancelarEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEspacoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoNovoEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(botaoSalvarEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(botaoCancelarEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovoEspaco)
                    .addComponent(botaoSalvarEspaco)
                    .addComponent(botaoCancelarEspaco))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneEspacoCafe)
                    .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPaneEspacoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaEspacosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEspacosMouseClicked
        Botoes(true,false,false);
        
        int index = tabelaEspacos.getSelectedRow();
        if (index >= 0 && index < Modelo.getRowCount()) {
            String temp[] = Modelo.getCoffeSpace(index);
            campoNomeEspaco.setText(temp[0]);
            campoLotacaoEspaco.setText(temp[1]);
        }
    }//GEN-LAST:event_tabelaEspacosMouseClicked

    private void botaoNovoEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoEspacoActionPerformed
        Botoes(false,true,true);
        ManipulaCampo("Limpa");
        
        int linhaCafe = tabelaEspacos.getRowCount();
        if (linhaCafe >= 2) {
            ManipulaCampo("Bloqueia");
            Botoes(false,false,false);
            JOptionPane.showMessageDialog(this, "Você já possui dois espaços de café cadastrados!");
        } else {
            ManipulaCampo("Desbloqueia");
            Botoes(false,true,true);
        }
    }//GEN-LAST:event_botaoNovoEspacoActionPerformed

    private void botaoSalvarEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarEspacoActionPerformed
        
        if ((campoNomeEspaco.getText() == null || campoNomeEspaco.getText().trim().isEmpty()) || (campoLotacaoEspaco.getText() == null || campoLotacaoEspaco.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Você precisa preencher todos os campos!");
            Botoes(false,true,true);
        } else {
            if (CoffeSpaceController.SaveSpace(campoNomeEspaco.getText(),Integer.parseInt(campoLotacaoEspaco.getText()))) {
                this.LoadTableSpace();
                JOptionPane.showMessageDialog(this, "Espaço de café salvo com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o espaço de café!");
            }

            Botoes(true,false,false);
            ManipulaCampo("Limpa");
            ManipulaCampo("Bloqueia");
        }
    }//GEN-LAST:event_botaoSalvarEspacoActionPerformed

    private void botaoCancelarEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEspacoActionPerformed
        Botoes(true,false,false);
        ManipulaCampo("Limpa");
        ManipulaCampo("Bloqueia");
    }//GEN-LAST:event_botaoCancelarEspacoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarEspaco;
    private javax.swing.JButton botaoNovoEspaco;
    private javax.swing.JButton botaoSalvarEspaco;
    private javax.swing.JTextField campoLotacaoEspaco;
    private javax.swing.JTextField campoNomeEspaco;
    private javax.swing.JLabel labelLotacao;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JScrollPane scrollPaneEspacoCafe;
    private javax.swing.JTable tabelaEspacos;
    // End of variables declaration//GEN-END:variables
}
