/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConsultDataController;
import util.ConsultDataTableModel;

/**
 *
 * @author tharl
 */
public class ConsultDataScreen extends javax.swing.JInternalFrame {

    ConsultDataTableModel Modelo;
    
    // Carrega a tabela de pessoas
    public void LoadTableConsult() {
        Modelo = new ConsultDataTableModel(ConsultDataController.getDados());
        tabelaDados.setModel(Modelo);
        
        tabelaDados.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaDados.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelaDados.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    // Carrega a tabela de pessoas
    public void LoadTableConsultSegunda() {
        Modelo = new ConsultDataTableModel(ConsultDataController.getDadosSegundo());
        tabelaDadosSegunda.setModel(Modelo);
        
        tabelaDadosSegunda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaDadosSegunda.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabelaDadosSegunda.getColumnModel().getColumn(2).setPreferredWidth(50);
    }
    
    
    /**
     * Creates new form ConsultDataScreen
     */
    public ConsultDataScreen() {
        initComponents();
        LoadTableConsult();
        LoadTableConsultSegunda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultar = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JButton();
        scrollPaneTabelaDados = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        scrollPaneTabelaDados1 = new javax.swing.JScrollPane();
        tabelaDadosSegunda = new javax.swing.JTable();
        labelTitleUm = new javax.swing.JLabel();
        LabelTitleDois = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consultar");
        setPreferredSize(new java.awt.Dimension(468, 447));

        panelConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelConsultar.setPreferredSize(new java.awt.Dimension(485, 100));

        labelNome.setText("Nome:");

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarLayout = new javax.swing.GroupLayout(panelConsultar);
        panelConsultar.setLayout(panelConsultarLayout);
        panelConsultarLayout.setHorizontalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(panelConsultarLayout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConsultarLayout.setVerticalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoConsultar)
                .addContainerGap())
        );

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pessoas", "Salas", "Espaços de Café"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTabelaDados.setViewportView(tabelaDados);

        tabelaDadosSegunda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pessoas", "Salas", "Espaços de Café"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTabelaDados1.setViewportView(tabelaDadosSegunda);

        labelTitleUm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitleUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleUm.setText("1ª Etapa do Treinamento");

        LabelTitleDois.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelTitleDois.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitleDois.setText("2ª Etapa do Treinamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addComponent(scrollPaneTabelaDados1)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitleUm)
                    .addComponent(LabelTitleDois))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(scrollPaneTabelaDados, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(scrollPaneTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitleUm)
                        .addGap(148, 148, 148)
                        .addComponent(LabelTitleDois)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTabelaDados1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(panelConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        String nomeConsultar = campoNome.getText();
        this.LoadTableConsult();
    }//GEN-LAST:event_botaoConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitleDois;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTitleUm;
    private javax.swing.JPanel panelConsultar;
    private javax.swing.JScrollPane scrollPaneTabelaDados;
    private javax.swing.JScrollPane scrollPaneTabelaDados1;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JTable tabelaDadosSegunda;
    // End of variables declaration//GEN-END:variables
}
