/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author tharl
 */
public class MenuScreen extends javax.swing.JFrame {

    /** Creates new form MenuScreen */
    public MenuScreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        pessoaMenuItem = new javax.swing.JMenuItem();
        salaMenuItem = new javax.swing.JMenuItem();
        espacoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Treinamento");
        setLocationByPlatform(true);
        setResizable(false);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        pessoaMenuItem.setMnemonic('o');
        pessoaMenuItem.setText("Pessoa");
        pessoaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(pessoaMenuItem);

        salaMenuItem.setMnemonic('s');
        salaMenuItem.setText("Sala");
        salaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(salaMenuItem);

        espacoMenuItem.setMnemonic('a');
        espacoMenuItem.setText("Espaço");
        espacoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(espacoMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaMenuItemActionPerformed
        PersonScreen personScreen = new PersonScreen();
        this.desktopPane.add(personScreen);
        personScreen.setVisible(true);
    }//GEN-LAST:event_pessoaMenuItemActionPerformed

    private void salaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaMenuItemActionPerformed
        EventRoomScreen eventRoomScreen = new EventRoomScreen();
        this.desktopPane.add(eventRoomScreen);
        eventRoomScreen.setVisible(true);
    }//GEN-LAST:event_salaMenuItemActionPerformed

    private void espacoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacoMenuItemActionPerformed
        CoffeSpaceScreen coffeSpaceScreen = new CoffeSpaceScreen();
        this.desktopPane.add(coffeSpaceScreen);
        coffeSpaceScreen.setVisible(true);
    }//GEN-LAST:event_espacoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem espacoMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pessoaMenuItem;
    private javax.swing.JMenuItem salaMenuItem;
    // End of variables declaration//GEN-END:variables

}
